/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_c5bcdb1f (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/zzteuolgibfbulqdavof/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// Create a singleton Supabase client to avoid connection issues
let supabaseClient: any = null;

const client = () => {
  if (!supabaseClient) {
    const url = Deno.env.get("SUPABASE_URL");
    const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    
    if (!url || !key) {
      throw new Error("SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set");
    }
    
    supabaseClient = createClient(url, key, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
        detectSessionInUrl: false
      }
    });
  }
  return supabaseClient;
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c5bcdb1f").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  
  try {
    const { data, error } = await supabase
      .from("kv_store_c5bcdb1f")
      .select("value")
      .eq("key", key)
      .maybeSingle();
    
    if (error) {
      console.error(`[KV] Error getting key ${key}:`, error);
      throw new Error(error.message);
    }
    
    return data?.value;
    
  } catch (error: any) {
    console.error(`[KV] Exception in get for ${key}:`, error);
    
    // If connection reset, return null instead of failing
    if (error.message?.includes('connection reset') || error.message?.includes('connection error')) {
      console.warn(`[KV] Connection error for key ${key}, returning null`);
      return null;
    }
    
    throw error;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c5bcdb1f").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c5bcdb1f").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c5bcdb1f").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c5bcdb1f").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  
  try {
    console.log(`[KV] Getting keys with prefix: ${prefix}`);
    
    const { data, error } = await supabase
      .from("kv_store_c5bcdb1f")
      .select("key, value")
      .like("key", prefix + "%");
    
    if (error) {
      console.error(`[KV] Error getting by prefix ${prefix}:`, error);
      throw new Error(error.message);
    }
    
    console.log(`[KV] Found ${data?.length || 0} records with prefix ${prefix}`);
    return data?.map((d) => d.value) ?? [];
    
  } catch (error: any) {
    console.error(`[KV] Exception in getByPrefix for ${prefix}:`, error);
    
    // If connection reset, return empty array instead of failing
    if (error.message?.includes('connection reset') || error.message?.includes('connection error')) {
      console.warn(`[KV] Connection error for prefix ${prefix}, returning empty array`);
      return [];
    }
    
    throw error;
  }
};